### ISSUE TITLE
Add to_list or to_dict to Response object?

### ISSUE THREAD

**Issue by ngoyal** [sis-cmdb/sis-python#5]
Would you be open to adding some methods on the `Response` object that returns the ._result property.  I.E. if we do `to_dict` on a response where `_result` is a list, then we throw an exception?  I ran into a bug where I was trying to do `response.get('foo', None)` i.e. a `dict.get` instead of the `__get_item__`.

**Comment by antongavrik** [comment]
to_dict(), to_list() methods have been added to the Response() as a part of 0.3.11. Thank you for the suggestion.
